tirgger: none
pr: none

stages:
  - stage: PlanDev
    displayName: 'PlanDev'
    jobs:
      - job: PlanDev
        displayName: 'PlanDev'
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            clean: true
          - task: TerraformInstaller@1
            displayName: Install Terraform 1.9.6
            inputs:
              terraformVersion: 1.9.6

          